### ISSUE TITLE
Add video and screenshot for failed tests

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-data-portal#3189]
https://playwright.tech/blog/record-your-browser-tests-with-playwright

https://github.com/actions/upload-artifact

```
- uses: actions/upload-artifact@v2
      if: ${{ failure() || success() }}
      with:
        name: Recordings
        path: videos/
```
